---
name: DBIx-TmpDB
abstract: 'Temporary database runner'
version: 0.02
author:
  - 'Alexander Lebedev <x-ander@alexplus.ru>'
license: perl
distribution_type: module
requires:
  DBI: 1.612
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.57_05'
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
no_index:
  directory:
    - t
